apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-metrics-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: grafana-cloud-metrics-credentials
  data:
    - secretKey: username
      remoteRef:
        key: grafana-credentials
        property: GCLOUD_HOSTED_METRICS_ID
    - secretKey: password
      remoteRef:
        key: grafana-credentials
        property: GCLOUD_K8S_RW_TOKEN
