{{- if .Values.letsencrypt.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.slicen.me
            solverName: linode
            config:
              apiKeySecretRef:
                name: linode-token
                key: LINODE_TOKEN
{{- else }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca
{{- end }}
