{{- if .Values.letsencrypt.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linode-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: linode-credentials
  data:
    - secretKey: token
      remoteRef:
        key: external-dns
        property: LINODE_TOKEN
{{- end }}
