{{- if not .Values.letsencrypt.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: root.{{ .Values.cluster.domain }}
  secretName: root-ca
  subject:
    organizations:
      - {{ .Values.cluster.domain }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: root-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}
