apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: authelia-users
  data:
    - secretKey: users_database.yml
      remoteRef:
        key: authelia-users
        property: users_database
