apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: authelia-oidc
  data:
    - secretKey: AUTHELIA_OIDC_HMAC_SECRET
      remoteRef:
        key: authelia-oidc
        property: AUTHELIA_OIDC_HMAC_SECRET
    - secretKey: AUTHELIA_OIDC_JWK_KEY
      remoteRef:
        key: authelia-oidc
        property: AUTHELIA_OIDC_JWK_KEY
    - secretKey: AUTHELIA_OIDC_ARGOCD_CLIENT_SECRET
      remoteRef:
        key: authelia-oidc
        property: AUTHELIA_OIDC_ARGOCD_CLIENT_SECRET
